FROM eclipse-temurin:17

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

COPY src ./src
COPY application-development.yml ./application.yml

CMD ["./mvnw", "spring-boot:run"]
